title: "Experience List"
date: 2020-10-21
---
author: v
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
@@ -13,3 +12,4 @@ github_username:  your-github-handle # DO NOT include the @ character, or else t

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
